name: Deploy Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build_and_push:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '21'

      - name: Build with Maven
        run: mvn versions:set -DnewVersion=${{ github.ref_name }}

      - name: Commit report
        run: |
          git config --global user.name 'CI Bot'
          git config --global user.email 'ci-bot@users.noreply.github.com'
          git commit -am "Bump version to ${{ github.ref_name }}"
          git push